### ISSUE TITLE
Warning: Permanently added '***' (ED25519) to the list of known hosts.

### ISSUE THREAD

**Issue by bigBron** [marcodallasanta/ssh-scp-deploy#20]
```log
👌 Executing pre-upload script...
Warning: Permanently added '***' (ED25519) to the list of known hosts.
pre_upload 👈
✅ Executed pre-upload script
🚚 Uploading via scp...
Warning: Permanently added '***' (ED25519) to the list of known hosts.
```

**Comment by marcodallasanta** [comment]
Hi and thanks for spending some time contributing.

Why is this an issue?
It's just the GitHub runner shell informing you it's going to add the host to which you are going to connect, to the list of known hosts `~/.ssh/known_hosts`.

If the problem is just seeing the warning, you can manually add an entry with the host in `~/.ssh/known_hosts` before using the action.

Otherwise you could invoke the action with:
```
with:
  ssh_options: -o StrictHostKeyChecking=no
```

And this should remove the warning.

**Comment by bigBron** [comment]
thk
